spring:
  security:
    oauth2:
      client:
        registration:
          aws:
            client-id: jsc6qbniq3ht5ivqnmjeu9ipi
            client-secret: to1nc7ja5ce0pihnfm03lv3rv1su8k1j7o9poa2ssq25elt5ib1
  webflux:
    hiddenmethod:
      filter:
        enabled: true             
server:
  ssl:
    key-store: classpath:secure.p12
    key-store-password: password
    key-password: password